# Site settings
title: Programación en R - 2017
email: lgmoyano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programación y análisis de datos en R con aplicaciones científicas
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: "@luisgmoyano"
github_username:  lgmoyano
# baseurl: /R-2017

# Build settings
markdown: kramdown
show_drafts: FALSE
plugins_dir: _plugins
paginate: 3
exclude: ["gulp", '*.org', 'reveal*']

theme: jekyll-theme-minimal